/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop.inventory.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.BillDao;
import dao.BookDao;
import dao.CategoryDao;
import dao.DbOperations;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Book;
import model.Category;
import model.Bill;

/**
 *
 * @author Renuka Gour
 */
public class PlaceOrder extends javax.swing.JFrame {
    // for which user

    public String userEmail;
    public int billId = 1;
    public int grandTotal = 0;
    public int price = 0;
    public int total = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    int stock;
    int NewQty;
    int oldQty;
    int bid;
    String category1;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();

    }

    public PlaceOrder(String email) {
        initComponents();
        txtTitle.setEditable(false);
        txtPrice.setEditable(false);
        txtTotal.setEditable(false);
        btnAddToCart.setEnabled(false);
        btnPrint.setEnabled(false);
        userEmail = email;

//        DefaultTableModel dtm = (DefaultTableModel) bookTable.getModel();
//        ArrayList<Book> list1 = BookDao.getAllRecords();
//        Iterator<Book> it1 = list1.iterator();
//        while (it1.hasNext()) {
//            Book book = it1.next();
//            dtm.addRow(new Object[]{book.getBid(), book.getTitle(), book.getAuthor(), book.getPublisher(), book.getCategory(), book.getPrice(), book.getQuantity()});
//
//        }
    }

    public void bookNameByCategory(String Category) {
        DefaultTableModel dtm = (DefaultTableModel) bookTable.getModel();
        dtm.setRowCount(0);
        ArrayList<Book> list = BookDao.gettAllRecordsByCategory(Category);
        Iterator<Book> it = list.iterator();
        while (it.hasNext()) {
            Book book = it.next();
            dtm.addRow(new Object[]{book.getBid(), book.getTitle(), book.getAuthor(), book.getPublisher(), book.getCategory(), book.getPrice(), book.getQuantity()});
        }

    }

    public void filterRecordsBytitle(String title, String Category) {
        DefaultTableModel dtm = (DefaultTableModel) bookTable.getModel();
        dtm.setRowCount(0);
        ArrayList<Book> list = BookDao.filterRecordsBytitle(title, Category);
        Iterator<Book> it = list.iterator();
        while (it.hasNext()) {
            Book book = it.next();
            dtm.addRow(new Object[]{book.getBid(), book.getTitle(), book.getAuthor(), book.getPublisher(), book.getCategory(), book.getPrice(), book.getQuantity()});
        }

    }

    public void clearBookFields() {
        txtTitle.setText("");
        txtPrice.setText("");
        txtTotal.setText("");
        txtQuantity.setText("");
        btnAddToCart.setEnabled(false);

    }

    public void validateFields() {
        String cname = txtCName.getText();
        String cmobilenumber = txtCMobileNumber.getText();
        String cemail = txtCEmail.getText();
        String caddress = txtcAddress.getText();
        if (!cname.equals("") && cmobilenumber.matches(mobileNumberPattern) && cmobilenumber.length() == 10 && cemail.matches(emailPattern) && grandTotal > 0 && !caddress.equals("")) {
            btnPrint.setEnabled(true);
        } else {
            btnPrint.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        labelBillid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        txtCEmail = new javax.swing.JTextField();
        txtCMobileNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelGrandTotal = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(250, 80));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Book Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Catergory");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, -1));

        txtTitle.setBackground(new java.awt.Color(255, 255, 204));
        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTitleKeyReleased(evt);
            }
        });
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 35));

        txtPrice.setBackground(new java.awt.Color(255, 255, 204));
        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 35));

        txtQuantity.setBackground(new java.awt.Color(255, 255, 204));
        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, 35));

        btnPrint.setBackground(new java.awt.Color(255, 255, 204));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btnPrint.setText("Generate Bill & Print ");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Books List");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, 20));

        txtSearch.setBackground(new java.awt.Color(255, 255, 204));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 310, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 34));

        btnAddToCart.setBackground(new java.awt.Color(255, 255, 204));
        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 140, 35));

        btnClear.setBackground(new java.awt.Color(255, 255, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 70, -1));

        txtTotal.setBackground(new java.awt.Color(255, 255, 204));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 100, 35));

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Price", "Quantity", "Total"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 560, 260));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bill ID :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 68, -1));

        labelBillid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelBillid.setText("--");
        getContentPane().add(labelBillid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 68, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Customer Details :- ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 140, -1));

        txtCName.setBackground(new java.awt.Color(255, 255, 204));
        txtCName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 290, 35));

        txtCEmail.setBackground(new java.awt.Color(255, 255, 204));
        txtCEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtCEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 290, 35));

        txtCMobileNumber.setBackground(new java.awt.Color(255, 255, 204));
        txtCMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCMobileNumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtCMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 290, 35));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 141, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 141, 26));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Mobile No.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 124, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Grand Total :-  Rs. ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 140, 20));

        labelGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelGrandTotal.setText("000");
        getContentPane().add(labelGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 68, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 35));
        jComboBox1.getAccessibleContext().setAccessibleName("");

        bookTable.setBackground(new java.awt.Color(255, 255, 204));
        bookTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Category", "Price", "Quantity"
            }
        ));
        bookTable.setRowHeight(25);
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 480, 260));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Book Shop Inventory System");

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Address");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        txtcAddress.setBackground(new java.awt.Color(255, 255, 204));
        txtcAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcAddressKeyReleased(evt);
            }
        });
        getContentPane().add(txtcAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 290, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTitleKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTitleKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        int quantity = Integer.parseInt(txtQuantity.getText());
        total = price * quantity;
        txtTotal.setText(String.valueOf(total));

    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String title = txtSearch.getText();
        String category = (String) jComboBox1.getSelectedItem();
        filterRecordsBytitle(title, category);


    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearBookFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased


    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();

        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this Book", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = jTable2.getModel();
            String total = model.getValueAt(index, 3).toString();
            int Qty = Integer.parseInt(model.getValueAt(index, 2).toString());
            String title = model.getValueAt(index, 0).toString();
            NewQty = Qty + oldQty;

            updateQuantity(NewQty, bid);
            bookNameByCategory(category1);

            grandTotal = grandTotal - Integer.parseInt(total);
            labelGrandTotal.setText(String.valueOf(grandTotal));
            //update quantity need to write
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtCNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNameKeyReleased
        // TODO add your handling code here:
        validateFields();

    }//GEN-LAST:event_txtCNameKeyReleased

    private void txtCEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEmailKeyReleased
        // TODO add your handling code here:
        validateFields();

    }//GEN-LAST:event_txtCEmailKeyReleased

    private void txtCMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMobileNumberKeyReleased
        // TODO add your handling code here:
        validateFields();

    }//GEN-LAST:event_txtCMobileNumberKeyReleased


    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        billId = Integer.parseInt(BillDao.getId());
        labelBillid.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> it = list.iterator();
        while (it.hasNext()) {
            Category categoryobj = it.next();
            jComboBox1.addItem(categoryobj.getName());

        }
        String category = (String) jComboBox1.getSelectedItem();
        bookNameByCategory(category);

    }//GEN-LAST:event_formComponentShown


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String category = (String) jComboBox1.getSelectedItem();
        bookNameByCategory(category);
    }//GEN-LAST:event_jComboBox1ActionPerformed
    //update quantity
    public static void updateQuantity(int NewQty, int bid) {
        String query = "update book set quantity='" + NewQty + "' where bid='" + bid + "'";
        DbOperations.setDataOrDelete(query, "");
    }


    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        int index = bookTable.getSelectedRow();
        TableModel model = bookTable.getModel();
        stock = Integer.parseInt(model.getValueAt(index, 6).toString());
        bid = Integer.parseInt(model.getValueAt(index, 0).toString());
        category1 = model.getValueAt(index, 4).toString();
        oldQty = Integer.parseInt(model.getValueAt(index, 6).toString());
        String quantity = txtQuantity.getText();
        if ((Integer.parseInt(quantity)) < 1) {
            JOptionPane.showMessageDialog(null, "Quantity Should be Positive");
            txtQuantity.setText("");
        } else if (stock < (Integer.parseInt(txtQuantity.getText()))) {
            JOptionPane.showMessageDialog(null, "Not Enough Stock");
            txtQuantity.setText("");
        } else {
            quantity = txtQuantity.getText();
            NewQty = stock - Integer.parseInt(quantity);
            updateQuantity(NewQty, bid);
            bookNameByCategory(category1);
            String title = txtTitle.getText();
            String price = String.valueOf(txtPrice.getText());
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.addRow(new Object[]{title, price, quantity, total});
            grandTotal = grandTotal + total;
            labelGrandTotal.setText(String.valueOf(grandTotal));
            clearBookFields();
            validateFields();
            oldQty = Integer.parseInt(model.getValueAt(index, 6).toString());
        }


    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        // TODO add your handling code here:
        int index = bookTable.getSelectedRow();
        TableModel model = bookTable.getModel();
        String Title = model.getValueAt(index, 1).toString();
        Book book = BookDao.getBookBytitle(Title);
        txtTitle.setText(book.getTitle());
        stock = book.getQuantity();
        txtPrice.setText(String.valueOf(book.getPrice()));
        txtTotal.setText(String.valueOf(book.getPrice()));//total for initial
        price = book.getPrice();
        total = book.getPrice();
        btnAddToCart.setEnabled(true);


    }//GEN-LAST:event_bookTableMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String cname = txtCName.getText();
        String cmobilenumber = txtCMobileNumber.getText();
        String cemail = txtCEmail.getText();
        String caddress =txtcAddress.getText();
        //import from java.texttext
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date(); //import from java.util
        String todayDate = dateFormat.format(date);
        String total = String.valueOf(grandTotal);
        String createdBy = userEmail;
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setName(cname);
        bill.setMobileNumber(cmobilenumber);
        bill.setEmail(cemail);
        bill.setDate(todayDate);
        bill.setTotal(this.total);
        bill.setCreatedBy(createdBy);
        bill.setAddress(caddress);
        BillDao.save(bill);//to save bill

        //creating Document
        String path = "E:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();

        try {

            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
            doc.open();
            Paragraph shopName = new Paragraph("                                                          Book Shop inventory System\n");
            doc.add(shopName);
            Paragraph star = new Paragraph("**************************************************************************************************************");
            doc.add(star);
            Paragraph paragraph3 = new Paragraph("\tBill ID:" + billId + "\nCustomer Name : " + cname + "\nTotal Paid :" + grandTotal+"\n Address : "+caddress+"\n");
            doc.add(paragraph3);
            doc.add(star);
            //insert pdf table
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Book Title");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String b = jTable2.getValueAt(i, 0).toString();
                String p = jTable2.getValueAt(i, 1).toString();
                String q = jTable2.getValueAt(i, 2).toString();
                String t = jTable2.getValueAt(i, 3).toString();
                tb1.addCell(b);
                tb1.addCell(p);
                tb1.addCell(q);
                tb1.addCell(t);
            }
            doc.add(tb1);
            doc.add(star);
            Paragraph thank = new Paragraph("Thank you, Please Visit Again");
            doc.add(thank);
            //open pdf
            OpenPdf.openById(String.valueOf(billId));

        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);


    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtcAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcAddressKeyReleased
        validateFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcAddressKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelBillid;
    private javax.swing.JLabel labelGrandTotal;
    private javax.swing.JTextField txtCEmail;
    private javax.swing.JTextField txtCMobileNumber;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcAddress;
    // End of variables declaration//GEN-END:variables
}
